#!/bin/sh
set -e
# Automatically added by dh_installinit
if ([ -x "/etc/init.d/ovn-host" ] || [ -e "/etc/init/ovn-host.conf" ]) && \
   [ "$1" = remove ]; then
	invoke-rc.d ovn-host stop || exit $?
fi
# End automatically added section
